WIP Add readme to workflows
halomod/TheHaloMod-SPA pull request #156
Opened 2021-04-08 08:30 UTC by aschnapp

### Overview
Just readme and documentation updates.

### Includes:
See files tab for reference

### Developer Checklist:
- [ ] The code follows the Quality Policy file on Google Drive
- [ ] My code has been developer-tested and includes unit tests
- [ ] I have considered proper use of exceptions
- [ ] I have eliminated IDE warnings

### Notes:
NA

### Refs:
- [HM-319](https://the-halo-mod.atlassian.net/browse/HM-319)

2021-04-13 03:16 UTC, vperuzzi approved these changes

2021-04-13 14:10 UTC, aneuhold commented
@aschnapp is this still a work in progress?

2021-04-14 17:29 UTC, aschnapp commented
@aneuhold mostly done, one last thing which is still getting resolved in slack

2021-04-15 07:25 UTC, aschnapp commented
@aneuhold this is done now.

2021-04-15 14:56 UTC, aneuhold requested changes
Looks great! Just needs one comment addressed and it is good.

2021-04-15 14:56 UTC, aneuhold commented on server/README.md
> +```
It looks like the new sections need to be added to the table of contents for this readme.

2021-04-16 10:48 UTC, aschnapp commented
@aneuhold done!

2021-04-17 02:18 UTC, aneuhold approved these changes
Looks good!

2021-04-17 02:19 UTC, merged