US338 Model Specific Error Reporting
halomod/TheHaloMod-SPA pull request #163
Opened 2021-04-19 21:10 UTC by Tengelma

### Overview
This enables users to report issues with a specific model by providing their contact details and a description of the bug itself. This information is sent to the server which generates and sends an email containing the user provided information alongside a toml representation of the relevant model.

To make this work, you need to provide flask with an email and password for some gmail account. Google's smtp server is used to send the email from that email to itself so it can be read later on.

I created an email for this for my own testing. You can use the following commands to load them into your environment.

export EMAIL_USERNAME=testingthm@gmail.com
export EMAIL_PASSWORD=ThisIsAPassword  

### Includes:
- See files changed

### Developer Checklist:
- [X] The code follows the Quality Policy file on Google Drive
- [N/A] My code has been developer-tested and includes unit tests
- [X] I have considered proper use of exceptions
- [X] I have eliminated IDE warnings
- [X] I have included tasks associated with this pull request in the Sprint Progress Sheet.

### Notes:
- Tests have been excluded as this would require us to include email and password details in the server's .yml or as a secret in GH actions which also doesn't make a whole lot of sense considering this is up to Steven.

### Refs:
- [Feat: ability to report a bug in a specific model](https://github.com/halomod/TheHaloMod-SPA/issues/135)

2021-04-20 01:46 UTC, aneuhold requested changes
Looks great! Just the one thing we discussed at the meeting and this is approved.

2021-04-20 01:46 UTC, aneuhold commented on server/halomod_app/endpoint_bugs.py
> +    )
It looks like this is the part where the "send to" address could be configured via environment variables like we discussed at the meeting :)

2021-04-21 16:04 UTC, aschnapp approved these changes
I'll approve for now. Looks good. 
Just fix the changes requested during the meeting before merging :)

2021-04-26 00:45 UTC, aneuhold approved these changes

2021-04-26 00:45 UTC, merged