US221 Form State Management [IN PROGRESS]
halomod/TheHaloMod-SPA pull request #58
Opened 2021-01-28 22:47 UTC by Tengelma

Hi all. This is an early pull request to get a couple of simple changes into dev --
- pushes our form initialization object to another file
- introduces rename functionality to the client/server (and corresponding tests on both sides)

I will be keeping this pull request open until I'm done with the US so I can get feedback & everyone can pull progress into their local branches as needed / desired.

2021-01-30 08:45 UTC, aschnapp requested changes
I sent the things I believe that can be changed in your slack pms

2021-01-30 20:35 UTC, Tengelma commented
> I sent the things I believe that can be changed in your slack pms

Recent commits did the following:
- Resolved the navbar issue
- Brought the loading indicator in from your branch
- Adjusted file structure like you suggested

I am reluctant to combine Edit/Create views because of the following reasons:
- Content and logic are substantially different (introducing 30 ternary operators makes code less readable)
- Clearer separation of concerns with different routes having their own file
- What would we even name the view that combines edit & create and has a boatload of conditional logic in their dependent on what route you're actually in?
- I get that its not DRY but this format is being reused ONCE and I think the gains in code clarity (both in the route structure and within the file itself) outweigh the benefit of forcing all these differences into a single Vue component.

2021-01-30 22:44 UTC, aneuhold requested changes
The buttons on the bottom left and the confirmation dialog when creating a new model look great! Love that addition 🌈. In general, the model naming, and creation process is awesome now. Great work on all that. 

Only a couple questions before approving, and also, the spacing for the models is quite large now. Does it need to be that large or can we narrow that down a bit? See below:

![image](https://user-images.githubusercontent.com/17774559/106369769-f9658400-6308-11eb-9888-1b7fe050256b.png)

This looks like it was a ton of work. Awesome job to you and Michael for getting this all together. 

P.S. Someone got their formatter to work! lol

2021-01-30 22:44 UTC, aneuhold commented on .github/workflows/client.yaml
> +        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}-1
Just out of curiosity, how did this addition of `-1` fix it?

2021-01-30 22:44 UTC, aneuhold commented on client/src/constants/forms.js
> +    props: {
Excellent. So much more clean.

2021-01-30 22:44 UTC, aneuhold commented on client/src/utils/Store.js
> +
Woot!

2021-01-30 22:53 UTC, Tengelma commented on .github/workflows/client.yaml
> +        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}-1
Ah, it didn't end up fixing it. Github's caching is a bit weird because you can't manually clear it. I kept hitting the same node_modules cache (that wasn't working because of some replace all I did at some point) and it led to repeated build failures so I was just trying to get a clean slate. 

Eventual solution was just to npm update locally, generate a new package-lock.json and ship that up instead. Thank you Stack Overflow !

2021-01-30 22:56 UTC, Tengelma commented
@aneuhold There's no great reason for the models being as spaced as they are. It's mainly just because what's displayed is an md-field and md-input under the hood and I didn't think to change it. I'll see if I can update the formatting soon.

2021-01-30 23:35 UTC, aneuhold commented on .github/workflows/client.yaml
> +        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}-1
Awesome. Can the key be changed back then really quick?

2021-01-31 04:54 UTC, Tengelma commented
@aneuhold Your concerns should be resolved. Lemme know if there's anything else to do.

2021-01-31 05:17 UTC, aneuhold approved these changes
Amazing! Looks fantastic 😄

2021-01-31 07:20 UTC, aschnapp commented
See Forms.vue in views
Just pushed an additional file that does not have any ternaries to review. Your changes are still there. If we decide to use yours, just delete this file before we merge. 

I am reluctant to combine Edit/Create views because of the following reasons:
- Content and logic are substantially different (introducing 30 ternary operators makes code less readable)
No ternaries
- Clearer separation of concerns with different routes having their own file
The largest part of it is a v-if
- What would we even name the view that combines edit & create and has a boatload of conditional logic in their dependent on what route you're actually in?
Naming should not be a reason to keep us from keeping it DRY

- I get that its not DRY but this format is being reused ONCE and I think the gains in code clarity (both in the route structure and within the file itself) outweigh the benefit of forcing all these differences into a single Vue component. 
We are going to be adding error reporting. Do we really want to be copying code between the two documents on every single change just to keep it in sync? You already had to add a loading indicator in the exact same place for both files, how many more are we going to be doing?

2021-02-01 09:30 UTC, aschnapp approved these changes

2021-02-01 09:46 UTC, merged